CREATE TABLE "AO_950DC3_TC_CUSTOM_EV_TYPES_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_CUSTOM_EV_TYPES" ;
CREATE TABLE "AO_950DC3_TC_EVENTS_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_EVENTS" ;
CREATE TABLE "AO_950DC3_TC_DISABLE_EV_TYPES_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_DISABLE_EV_TYPES" ;
CREATE TABLE "AO_950DC3_TC_EVENTS_EXCL_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_EVENTS_EXCL" ;
CREATE TABLE "AO_950DC3_TC_EVENTS_INVITEES_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_EVENTS_INVITEES" ;
CREATE TABLE "AO_950DC3_TC_JIRA_REMI_EVENTS_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_JIRA_REMI_EVENTS" ;
CREATE TABLE "AO_950DC3_TC_REMINDER_SETTINGS_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_REMINDER_SETTINGS" ;
CREATE TABLE "AO_950DC3_TC_REMINDER_USERS_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_REMINDER_USERS" ;
CREATE TABLE "AO_950DC3_TC_SUBCALS_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_SUBCALS" ;
CREATE TABLE "AO_950DC3_TC_SUBCALS_IN_SPACE_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_SUBCALS_IN_SPACE" ;
CREATE TABLE "AO_950DC3_TC_SUBCALS_PRIV_GRP_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_SUBCALS_PRIV_GRP" ;
CREATE TABLE "AO_950DC3_TC_SUBCALS_PRIV_USR_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_SUBCALS_PRIV_USR" ;
CREATE TABLE "AO_950DC3_TC_SUBCALS_PROPS_BACKUP" AS
SELECT * FROM "AO_950DC3_TC_SUBCALS_PROPS" ;
