INSERT INTO "AO_950DC3_TC_CUSTOM_EV_TYPES" 
SELECT * FROM "AO_950DC3_TC_CUSTOM_EV_TYPES_BACKUP";
INSERT INTO "AO_950DC3_TC_EVENTS" 
SELECT * FROM "AO_950DC3_TC_EVENTS_BACKUP" ;
INSERT INTO "AO_950DC3_TC_DISABLE_EV_TYPES" 
SELECT * FROM "AO_950DC3_TC_DISABLE_EV_TYPES_BACKUP" ;  
INSERT INTO "AO_950DC3_TC_EVENTS_EXCL" 
SELECT * FROM "AO_950DC3_TC_EVENTS_EXCL_BACKUP" ;   
INSERT INTO "AO_950DC3_TC_EVENTS_INVITEES" 
SELECT * FROM "AO_950DC3_TC_EVENTS_INVITEES_BACKUP" ;  
INSERT INTO "AO_950DC3_TC_JIRA_REMI_EVENTS" 
SELECT * FROM "AO_950DC3_TC_JIRA_REMI_EVENTS_BACKUP" ;  
INSERT INTO "AO_950DC3_TC_REMINDER_SETTINGS" 
SELECT * FROM "AO_950DC3_TC_REMINDER_SETTINGS_BACKUP" ;  
INSERT INTO "AO_950DC3_TC_REMINDER_USERS" 
SELECT * FROM "AO_950DC3_TC_REMINDER_USERS_BACKUP" ;  
INSERT INTO "AO_950DC3_TC_SUBCALS" 
SELECT * FROM "AO_950DC3_TC_SUBCALS_BACKUP" ;  
INSERT INTO "AO_950DC3_TC_SUBCALS_IN_SPACE" 
SELECT * FROM "AO_950DC3_TC_SUBCALS_IN_SPACE_BACKUP" ;  
INSERT INTO "AO_950DC3_TC_SUBCALS_PRIV_GRP" 
SELECT * FROM "AO_950DC3_TC_SUBCALS_PRIV_GRP_BACKUP" ; 
INSERT INTO "AO_950DC3_TC_SUBCALS_PRIV_USR" 
SELECT * FROM "AO_950DC3_TC_SUBCALS_PRIV_USR_BACKUP" ;   
INSERT INTO "AO_950DC3_TC_SUBCALS_PROPS" 
SELECT * FROM "AO_950DC3_TC_SUBCALS_PROPS_BACKUP" ;